'use client'
import { ReactNode } from 'react'

import type { AppProps } from 'next/app'
import { ThemeProvider } from 'next-themes'

import './global.css' // css in all pages

import Button from './components/Button'

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout(
  { children }: { children: ReactNode },
  { Component, pageProps }: AppProps,
) {
  return (
    <html lang="en">
      <body className="bg-main-background p-6 max-w-sm mx-auto">
        <ThemeProvider attribute="class">
          <h1 className="text-2xl text-dark-background dark:text-light-background font-bold flex gap-2">
            Element in all pages
            <Button />
          </h1>
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
