import { ReactNode } from 'react'

import './global.css' // css in all pages

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className="bg-main-background p-6 max-w-sm mx-auto">
        <h1 className="text-2xl text-primary-text font-bold flex gap-2">
          Element in all pages
        </h1>
        {children}
      </body>
    </html>
  )
}
