import { ReactNode } from 'react'

import './global.css' // css in all pages

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>
        <h1>Element in all pages</h1>
        {children}
      </body>
    </html>
  )
}
